config/routes.rb
Rails.application.routes.draw do
  root 'players#index', defaults: { format: :json }
  resources :matchmaking, only: [:new], defaults: { format: :json }
  resources :matchmaking, only: [:create]
  resources :match, only: [:index]
  resources :players, only: [:index, :show], defaults: { format: :json }
  resources :champions, only: [:index]
end

app/models/player.rb
require 'TrueSkill'

class Player < ActiveRecord::Base
  validates :name, presence: true
  validates :summoner_id, presence: true

  before_create :set_default_rating

  def wins
    MatchPlayer.where(player_id: self.id, win: true).count
  end

  def losses
    MatchPlayer.where(player_id: self.id, win: false).count
  end

  def trueskill
    self.rating - 3 * self.standard_deviation
  end

  def champion_stats
    player_matches = MatchPlayer.where(player_id: self.id)
    champion_ids = player_matches
      .group(:champion_id)
      .count
      .keys

    stats = champion_ids.map do |champion_id|
      champion_matches = player_matches.where(champion_id: champion_id)
      champion_wins = champion_matches.where(win: true).count
      champion_losses = champion_matches.where(win: false).count
      {
        id: champion_id,
        wins: champion_wins,
        losses: champion_losses,
        winrate: (champion_wins.to_f / (champion_wins + champion_losses) * 100).round(2)
      }
    end

    stats.sort_by { |stat| [stat[:winrate], stat[:wins]] }.reverse
  end

  private

  def set_default_rating
    rating = Rating.new

    self.rating = rating.mu
    self.standard_deviation = rating.sigma
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :cors_set_access_control_headers

  def index
    @players = Player.all.sort_by(&:trueskill).reverse
  end

  def show
    @player = Player.find(params[:id])
  end

  private

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/helpers/players_helper.rb
module PlayersHelper
  def players_by_rank(players)
    players.sort { |a, b| b.trueskill <=> a.trueskill }
  end
end

app/views/players/index.html.erb
<h3 class="text-center">Players</h3>
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Rank</th>
				<th>Summoner</th>
				<th>Rating</th>
				<th>Wins</th>
				<th>Losses</th>
			</tr>
		</thead>
		<tbody>
			<% players_by_rank(@players).each.with_index do |player, i| %>
				<tr>
					<td><%= i + 1 %></td>
					<td><%= link_to player.name, player_path(player) %></td>
					<td><%= player.trueskill.round(3) %></td>
					<td><%= player.wins %></td>
					<td><%= player.losses %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/players/show.html.erb
<h3 class="text-center"><%= @player.name %></h3>
<div class="container">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Rank</th>
				<th>Champion</th>
				<th>Winrate</th>
				<th>Wins</th>
				<th>Losses</th>
			</tr>
		</thead>
		<tbody>
			<% champion_map = ChampionMap.new %>
			<% @player.champion_stats.each.with_index do |champion, i| %>
				<tr>
					<td><%= i + 1%></td>
					<td><%= champion_map.by_id(champion[:id]) %></td>
					<td><%= champion[:winrate] %></td>
					<td><%= champion[:wins] %></td>
					<td><%= champion[:losses] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>