config/routes.rb
Rails.application.routes.draw do
  root 'players#index', defaults: { format: :json }
  resources :matchmaking, only: [:new], defaults: { format: :json }
  resources :matchmaking, only: [:create]
  resources :match, only: [:index]
  resources :players, only: [:index, :show], defaults: { format: :json }
  resources :champions, only: [:index]
end

app/models/matchmaking.rb
class Matchmaking
end

app/controllers/matchmaking_controller.rb
class MatchmakingController < ApplicationController
  def new
    @players = Player.order(:name).all
  end

  def create
    selected_players = params['selected_players']

    if selected_players && selected_players.size == 10
      @selected_player_ids = selected_players.map(&:to_i)
      render :show
    else
      flash[:notice] = "Please select 10 players"
      redirect_to new_matchmaking_path
    end
  end
end

app/helpers/matchmaking_helper.rb
module MatchmakingHelper
  def create_teams(selected_player_ids)
    best_match(selected_player_ids).map do |team|
      team.map { |player_id| Player.find(player_id) }
    end
  end

  private

  def best_match(selected_player_ids)
    team_combos(selected_player_ids).max_by { |team_combo| match_quality(team_combo) }
  end

  def team_combos(selected_player_ids)
    team_1_combos = selected_player_ids.combination(5).to_a
    team_2_combos = team_1_combos.map do |team|
      selected_player_ids.reject { |id| team.include?(id) }
    end

    (0..team_1_combos.length - 1).map do |i|
      [team_1_combos[i], team_2_combos[i]]
    end
  end

  def match_quality(team_combo)
    teams_ratings = team_combo.map do |team|
      team.map do |player_id|
        player = Player.find(player_id)
        Rating.new(player.rating, player.standard_deviation)
      end
    end

    g().match_quality(teams_ratings)
  end
end

app/views/matchmaking/new.html.erb
<h3 class="text-center">Matchmaking</h3>
<div class="container">
	<% if flash[:notice] %>
		<div class="alert alert-danger"><%= flash[:notice] %></div>
	<% end %>

	<%= form_tag matchmaking_index_path, method: :post do %>
		<% @players.each do |player| %>
			<div class="checkbox">
				<label><%= check_box_tag 'selected_players[]', player.id %><%= player.name %></label>
			</div>
		<% end %>
		<%= submit_tag "Create Match", class: "btn btn-success" %>
	<% end %>
</div>

app/views/matchmaking/show.html.erb
<div class="container">
	<div class="row">
		<% create_teams(@selected_player_ids).each.with_index do |team, i| %>
			<div class="col-sm-6 col-md-6 text-center">
				<h3>Team <%= i + 1 %></h3>
				<div>
					<% team.each do |player| %>
						<div><%= player.name %></div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>